# Generated by Django 5.1.7 on 2025-03-14 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
            },
        ),
        migrations.CreateModel(
            name='ViPNetNetNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vipnet_net_number', models.CharField(max_length=5, unique=True, verbose_name='Номер сети')),
                ('vipnet_net_description', models.CharField(max_length=255, verbose_name='Описание сети')),
            ],
            options={
                'verbose_name': 'ViPNet сеть',
                'verbose_name_plural': 'ViPNet сети',
                'ordering': ['vipnet_net_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='clientname',
            options={'ordering': ['client_name'], 'verbose_name': 'Абонент сети', 'verbose_name_plural': 'Абоненты сети'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['full_name'], 'verbose_name': 'Владелец', 'verbose_name_plural': 'Владельцы'},
        ),
        migrations.RemoveField(
            model_name='owner',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='clientname',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='NewAbonent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owners.clientname', verbose_name='Клиент')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owners.owner', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абонент',
                'ordering': ['owner', 'client'],
            },
        ),
        migrations.AddField(
            model_name='clientname',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Owners.platform', verbose_name='Платформа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientname',
            name='net_number',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Owners.vipnetnetnumber', verbose_name='Номер сети'),
            preserve_default=False,
        ),
    ]
