# Generated by Django 5.1.7 on 2025-03-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0002_platform_vipnetnetnumber_alter_clientname_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientname',
            name='net_number',
        ),
        migrations.RemoveField(
            model_name='clientname',
            name='platform',
        ),
    ]
