# Generated by Django 5.1.7 on 2025-03-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0003_remove_clientname_net_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientname',
            options={'ordering': ['client_name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='newabonent',
            options={'ordering': ['owner', 'client'], 'verbose_name': 'Абонент', 'verbose_name_plural': 'Абоненты'},
        ),
    ]
