# Generated by Django 5.1.7 on 2025-04-18 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0004_alter_clientname_options_alter_newabonent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientname',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Наименование клиента'),
        ),
        migrations.AlterField(
            model_name='newabonent',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owners.owner', verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
