# Generated by Django 5.1.7 on 2025-04-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0005_alter_clientname_client_name_alter_newabonent_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ФИО полностью'),
        ),
    ]
