# Generated by Django 5.1.7 on 2025-04-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0006_alter_owner_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['platform_name'], 'verbose_name': 'Платформа', 'verbose_name_plural': 'Платформы'},
        ),
    ]
