# Generated by Django 5.1.7 on 2025-06-16 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0007_alter_platform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newabonent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Owners.clientname', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='newabonent',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Owners.owner', verbose_name='ФИО владельца'),
        ),
    ]
