# Generated by Django 5.2.5 on 2025-12-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0008_alter_newabonent_client_alter_newabonent_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='newabonent',
            name='iccid',
            field=models.CharField(blank=True, max_length=255, verbose_name='ICCID'),
        ),
        migrations.AddField(
            model_name='newabonent',
            name='imei',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMEI'),
        ),
        migrations.AddField(
            model_name='newabonent',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='newabonent',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='S/N'),
        ),
    ]
