# Generated by Django 5.2.5 on 2025-12-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0009_newabonent_iccid_newabonent_imei_newabonent_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newabonent',
            name='ogv',
            field=models.CharField(blank=True, max_length=255, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='newabonent',
            name='imei',
            field=models.TextField(blank=True, max_length=255, verbose_name='IMEI'),
        ),
    ]
