# Generated by Django 5.2.5 on 2025-12-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0010_newabonent_ogv_alter_newabonent_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='newabonent',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
