# Generated by Django 5.2.5 on 2025-12-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0011_newabonent_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newabonent',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID узла'),
        ),
    ]
