# Generated by Django 5.2.5 on 2025-12-23 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0012_newabonent_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='newabonent',
            name='net_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Owners.vipnetnetnumber', verbose_name='Сеть'),
        ),
    ]
