# Generated by Django 5.2.5 on 2025-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0013_newabonent_net_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newabonent',
            unique_together={('owner', 'client')},
        ),
    ]
