# Generated by Django 5.2.5 on 2025-12-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0014_alter_newabonent_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newabonent',
            options={'ordering': ['client', 'owner', 'ogv'], 'verbose_name': 'Абонент', 'verbose_name_plural': 'Абоненты'},
        ),
    ]
