# Generated by Django 5.2.5 on 2025-12-25 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0015_alter_newabonent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newabonent',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Owners.platform', verbose_name='Платформа'),
        ),
    ]
