# Generated by Django 5.2.5 on 2025-12-25 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0016_newabonent_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newabonent',
            name='net_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Owners.vipnetnetnumber', verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='newabonent',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Owners.platform', verbose_name='Платформа'),
        ),
    ]
