# Generated by Django 5.2.5 on 2025-12-23 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Licenses', '0004_alter_license_options_alter_license_unique_together'),
        ('Owners', '0009_newabonent_iccid_newabonent_imei_newabonent_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Основание',
                'verbose_name_plural': 'Основания',
            },
        ),
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_released', 'Заявка'), ('released', 'Подготовлен'), ('received', 'Выдан')], default='not_released', max_length=20, verbose_name='Статус')),
                ('log_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='№ в журнале')),
                ('date_of_request', models.DateField(blank=True, null=True, verbose_name='Дата запроса')),
                ('date_of_receipt', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('number_naumen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер Naumen')),
                ('number_elk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер ЕЛК')),
                ('ogv', models.TextField(max_length=255, verbose_name='ОГВ')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='dst')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('use_license', models.BooleanField(default=False, verbose_name='Используется лицензия')),
                ('abonents', models.ManyToManyField(to='Owners.newabonent', verbose_name='Абоненты')),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Issuance.authority', verbose_name='Основание')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Licenses.license', verbose_name='Лицензия')),
                ('net_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Owners.vipnetnetnumber', verbose_name='Номер сети')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Owners.platform', verbose_name='Платформа')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Журнал',
                'ordering': ['-log_number', '-date_of_request', 'status', '-date_of_receipt', '-number_naumen', '-number_elk'],
            },
        ),
    ]
