# Generated by Django 5.1.7 on 2025-04-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает получателя'), ('completed', 'Выдано')], default='pending', max_length=20, verbose_name='Статус')),
                ('number_naumen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер Naumen')),
                ('date', models.DateField(verbose_name='Предполагаемая дата получения')),
                ('receiving_time', models.TimeField(blank=True, null=True, verbose_name='Время получения')),
                ('ogv', models.CharField(max_length=255, verbose_name='Заявитель')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Всего dst')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Запись на получение',
                'verbose_name_plural': 'Записи на получение',
                'ordering': ['-date'],
            },
        ),
    ]
