# Generated by Django 5.2.5 on 2025-12-23 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issuance', '0001_initial'),
        ('Queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newrecipient',
            options={'ordering': ['-created_at', '-date'], 'verbose_name': 'Запись на получение', 'verbose_name_plural': 'Записи на получение'},
        ),
        migrations.AddField(
            model_name='newrecipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания записи'),
        ),
        migrations.AddField(
            model_name='newrecipient',
            name='number_elk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер ЕЛК'),
        ),
        migrations.AddField(
            model_name='newrecipient',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Issuance.logbook', verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='newrecipient',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Предполагаемая дата получения'),
        ),
        migrations.AlterField(
            model_name='newrecipient',
            name='ogv',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='newrecipient',
            name='status',
            field=models.CharField(choices=[('released', 'Выпущено'), ('pending', 'Ожидает получателя'), ('completed', 'Выдано')], default='released', max_length=20, verbose_name='Статус'),
        ),
    ]
