# Generated by Django 5.2.5 on 2025-12-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owners', '0008_alter_newabonent_client_alter_newabonent_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата запроса')),
                ('number_naumen', models.CharField(blank=True, max_length=255, verbose_name='Номер Naumen')),
                ('number_elk', models.CharField(blank=True, max_length=255, verbose_name='Номер ЕЛК')),
                ('ogv', models.CharField(max_length=255, verbose_name='ОГВ')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='dst')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('abonents', models.ManyToManyField(to='Owners.newabonent', verbose_name='Абоненты')),
                ('net_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owners.vipnetnetnumber', verbose_name='Номер сети')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owners.platform', verbose_name='Платформа')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ['date', 'number_naumen', 'number_elk', 'ogv', 'amount', 'net_number'],
            },
        ),
    ]
