# Generated by Django 5.2.5 on 2025-12-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Licenses', '0001_add_new_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_number', models.PositiveIntegerField(db_index=True, verbose_name='№ сети')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('inn', models.PositiveBigIntegerField(verbose_name='ИНН')),
                ('license_object', models.CharField(max_length=255, verbose_name='Объект лицензии')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Срок действия лицензии')),
                ('total_received', models.PositiveIntegerField(default=0, verbose_name='Количество поступивших лицензий')),
                ('last_replenishment', models.DateField(blank=True, null=True, verbose_name='Дата последнего пополнения')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='Использовано лицензий')),
                ('free', models.IntegerField(default=0, verbose_name='Свободно лицензий')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ['organization_name', 'inn', 'license_object', 'valid_until'],
                'unique_together': {('inn', 'organization_name', 'license_object')},
            },
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата поступления')),
                ('request_number', models.CharField(max_length=255, verbose_name='Номер заявки')),
                ('network_number', models.PositiveIntegerField(verbose_name='№ сети')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('inn', models.PositiveBigIntegerField(verbose_name='ИНН')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Срок действия лицензии')),
                ('license_object', models.CharField(max_length=255, verbose_name='Объект лицензии')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество по лицензии')),
                ('uploaded', models.BooleanField(default=False, verbose_name='Статус загрузки в сеть')),
                ('uploaded_date', models.DateField(blank=True, null=True, verbose_name='Дата загрузки в сеть')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='Licenses.license', verbose_name='Лицензия (связь)')),
            ],
            options={
                'verbose_name': 'Поступление',
                'verbose_name_plural': 'Поступления',
                'ordering': ['-date', 'request_number', 'organization_name'],
            },
        ),
    ]
