# Generated by Django 5.2.5 on 2025-12-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0002_initial'),
    ]

    operations = [
    ]
