# Generated by Django 5.2.5 on 2025-12-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licenses', '0003_add_new_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['organization_name', 'inn', 'license_object'], 'verbose_name': 'Лицензия', 'verbose_name_plural': 'Лицензии'},
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('inn', 'organization_name', 'license_object', 'valid_until')},
        ),
    ]
